In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
pd.read_excel("BTC-USD.xlsx").head()

Date        Open        High         Low       Close   Adj Close  \
0  2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1  2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2  2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   
3  2014-09-20  394.673004  423.295990  389.882996  408.903992  408.903992   
4  2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0  
3  36863600.0  
4  26580100.0

In [4]:
BTC= pd.read_excel("BTC-USD.xlsx")

In [5]:
BTC.head(3)

Date        Open        High         Low       Close   Adj Close  \
0  2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1  2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2  2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0

In [6]:
BTC.shape

(2437, 7)

In [7]:
import pandas as pd
import numpy as np

In [8]:
inputs = {
    'open': np.random.random(5),
    'high': np.random.random(5),
    'low': np.random.random(5),
    'close': np.random.random(5),
    'volume': np.random.random(5)
}

In [9]:
print(type(inputs))
inputs

<class 'dict'>


{'open': array([0.72932847, 0.8281912 , 0.88606766, 0.36134283, 0.10662372]),
 'high': array([0.6099038 , 0.69609661, 0.36526924, 0.13369664, 0.81082501]),
 'low': array([0.02818916, 0.63585756, 0.45272582, 0.68764193, 0.10377343]),
 'close': array([0.92753694, 0.28134057, 0.63354322, 0.3480469 , 0.57338091]),
 'volume': array([0.26170611, 0.77538944, 0.99823968, 0.27265469, 0.33701595])}

In [10]:
print(type(inputs["open"]))
inputs["open"]

<class 'numpy.ndarray'>


array([0.72932847, 0.8281912 , 0.88606766, 0.36134283, 0.10662372])

In [11]:
print(type(np.random.random(5)))
np.random.random(5)

<class 'numpy.ndarray'>


array([0.34604032, 0.93495579, 0.80672189, 0.25437197, 0.1081357 ])

In [12]:
BTC.head()

Date        Open        High         Low       Close   Adj Close  \
0  2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1  2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2  2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   
3  2014-09-20  394.673004  423.295990  389.882996  408.903992  408.903992   
4  2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0  
3  36863600.0  
4  26580100.0

In [13]:
print(type(BTC["Open"]))
BTC["Open"]

<class 'pandas.core.series.Series'>


0         465.864014
1         456.859985
2         424.102997
3         394.673004
4         408.084991
            ...     
2432    49855.496094
2433    46716.636719
2434    46415.898438
2435    43488.058594
2436    42673.000000
Name: Open, Length: 2437, dtype: float64

In [14]:
inputs = {
    'open': BTC["Open"],
    'high': BTC["High"],
    'low':  BTC["Low"],
    'close':  BTC["Adj Close"],
    'volume': BTC["Volume"]
}

In [15]:
from talib.abstract import *

In [16]:
inputs["open"]

0         465.864014
1         456.859985
2         424.102997
3         394.673004
4         408.084991
            ...     
2432    49855.496094
2433    46716.636719
2434    46415.898438
2435    43488.058594
2436    42673.000000
Name: Open, Length: 2437, dtype: float64

In [17]:
pd.isna(BTC)

Date   Open   High    Low  Close  Adj Close  Volume
0     False  False  False  False  False      False   False
1     False  False  False  False  False      False   False
2     False  False  False  False  False      False   False
3     False  False  False  False  False      False   False
4     False  False  False  False  False      False   False
...     ...    ...    ...    ...    ...        ...     ...
2432  False  False  False  False  False      False   False
2433  False  False  False  False  False      False   False
2434  False  False  False  False  False      False   False
2435  False  False  False  False  False      False   False
2436  False  False  False  False  False      False   False

[2437 rows x 7 columns]

In [18]:
BTC.isnull().values.any()

True

In [19]:
pd.DataFrame(BTC).dropna()

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2432  2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2433  2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2434  2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2435  2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2436  2021-05-19  42673.000000  43546.117188  38787.902344  39321.777344   

         Adj Close        Volume  
0       457.334015  2.105680e+07  
1       424.440002  3.448320e+07  
2       394.795990  3.791970e+07  
3       408.903992  3.686360e+07  
4       398.821014  2.658010e+07  
...            ...           ...  
2432  46760.187500  5.916105e+10  
2433  46456.058594  6.404787e+10  
2434  43537.511719  7.490364e+10  
2435  42909.402344  5.618737e+10  
2436  39321.777344  6.756428e+10  

[2433 rows x 7 columns]

In [20]:
modify_BTC = pd.DataFrame(BTC).dropna()

In [21]:
modify_BTC = modify_BTC.reset_index().drop(columns=['index'])

In [22]:
modify_BTC

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2428  2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429  2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430  2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431  2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432  2021-05-19  42673.000000  43546.117188  38787.902344  39321.777344   

         Adj Close        Volume  
0       457.334015  2.105680e+07  
1       424.440002  3.448320e+07  
2       394.795990  3.791970e+07  
3       408.903992  3.686360e+07  
4       398.821014  2.658010e+07  
...            ...           ...  
2428  46760.187500  5.916105e+10  
2429  46456.058594  6.404787e+10  
2430  43537.511719  7.490364e+10  
2431  42909.402344  5.618737e+10  
2432  39321.777344  6.756428e+10  

[2433 rows x 7 columns]

In [23]:
inputs = {
    'open': modify_BTC["Open"],
    'high': modify_BTC["High"],
    'low':  modify_BTC["Low"],
    'close':  modify_BTC["Adj Close"],
    'volume': modify_BTC["Volume"]
}

In [24]:
pd.DataFrame(SMA(inputs, timeperiod = 5, price='open')).head(10)

0
0         NaN
1         NaN
2         NaN
3         NaN
4  429.916998
5  416.564197
6  405.610602
7  407.940204
8  413.636804
9  414.305603

In [25]:
open_5ma   = SMA(inputs, timeperiod = 5, price='open')
close_5ma  = SMA(inputs, timeperiod = 5, price='close')
close_10ma = SMA(inputs, timeperiod = 10, price='close')
close_20ma = SMA(inputs, timeperiod = 20, price='close')

In [26]:
modify_BTC.head(3)

Date        Open        High         Low       Close   Adj Close  \
0  2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1  2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2  2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0

In [27]:
open_5ma

array([          nan,           nan,           nan, ..., 48481.2890628,
       47231.8140628, 45829.817969 ])

In [28]:
modify_BTC["open_5ma"]=open_5ma
modify_BTC["close_5ma"]=open_5ma
modify_BTC["close_10ma"]=open_5ma
modify_BTC["close_20ma"]=open_5ma

In [29]:
modify_BTC

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2428  2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429  2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430  2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431  2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432  2021-05-19  42673.000000  43546.117188  38787.902344  39321.777344   

         Adj Close        Volume      open_5ma     close_5ma    close_10ma  \
0       457.334015  2.105680e+07           NaN           NaN           NaN   
1       424.440002  3.448320e+07           NaN           NaN           NaN   
2       394.795990  3.791970e+07           NaN           NaN           NaN   
3       408.903992  3.686360e+07           NaN           NaN           NaN   
4       398.821014  2.658010e+07    429.916998    429.916998    429.916998   
...            ...           ...           ...           ...           ...   
2428  46760.187500  5.916105e+10  52367.136719  52367.136719  52367.136719   
2429  46456.058594  6.404787e+10  50541.015625  50541.015625  50541.015625   
2430  43537.511719  7.490364e+10  48481.289063  48481.289063  48481.289063   
2431  42909.402344  5.618737e+10  47231.814063  47231.814063  47231.814063   
2432  39321.777344  6.756428e+10  45829.817969  45829.817969  45829.817969   

        close_20ma  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4       429.916998  
...            ...  
2428  52367.136719  
2429  50541.015625  
2430  48481.289063  
2431  47231.814063  
2432  45829.817969  

[2433 rows x 11 columns]

In [30]:
modify_BTC["y"]=None

In [31]:
modify_BTC

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2428  2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429  2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430  2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431  2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432  2021-05-19  42673.000000  43546.117188  38787.902344  39321.777344   

         Adj Close        Volume      open_5ma     close_5ma    close_10ma  \
0       457.334015  2.105680e+07           NaN           NaN           NaN   
1       424.440002  3.448320e+07           NaN           NaN           NaN   
2       394.795990  3.791970e+07           NaN           NaN           NaN   
3       408.903992  3.686360e+07           NaN           NaN           NaN   
4       398.821014  2.658010e+07    429.916998    429.916998    429.916998   
...            ...           ...           ...           ...           ...   
2428  46760.187500  5.916105e+10  52367.136719  52367.136719  52367.136719   
2429  46456.058594  6.404787e+10  50541.015625  50541.015625  50541.015625   
2430  43537.511719  7.490364e+10  48481.289063  48481.289063  48481.289063   
2431  42909.402344  5.618737e+10  47231.814063  47231.814063  47231.814063   
2432  39321.777344  6.756428e+10  45829.817969  45829.817969  45829.817969   

        close_20ma     y  
0              NaN  None  
1              NaN  None  
2              NaN  None  
3              NaN  None  
4       429.916998  None  
...            ...   ...  
2428  52367.136719  None  
2429  50541.015625  None  
2430  48481.289063  None  
2431  47231.814063  None  
2432  45829.817969  None  

[2433 rows x 12 columns]

In [32]:
import math

In [33]:
math.log(120,10)

2.0791812460476247

In [34]:
modify_BTC.iloc[1,5]

424.440002

In [35]:
math.log(modify_BTC.iloc[1,5]/modify_BTC.iloc[0, 5] ,10)

-0.03241719606846411

In [37]:
modify_BTC.shape[0]

2433

In [38]:
for i in range(0,modify_BTC.shape[0]-1):
    modify_BTC.iloc[i,-1]=math.log(modify_BTC.iloc[i+1, 5]/modify_BTC.iloc[i, 5] , 10)

In [39]:
modify_BTC

Date          Open          High           Low         Close  \
0     2014-09-17    465.864014    468.174011    452.421997    457.334015   
1     2014-09-18    456.859985    456.859985    413.104004    424.440002   
2     2014-09-19    424.102997    427.834991    384.532013    394.795990   
3     2014-09-20    394.673004    423.295990    389.882996    408.903992   
4     2014-09-21    408.084991    412.425995    393.181000    398.821014   
...          ...           ...           ...           ...           ...   
2428  2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429  2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430  2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431  2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432  2021-05-19  42673.000000  43546.117188  38787.902344  39321.777344   

         Adj Close        Volume      open_5ma     close_5ma    close_10ma  \
0       457.334015  2.105680e+07           NaN           NaN           NaN   
1       424.440002  3.448320e+07           NaN           NaN           NaN   
2       394.795990  3.791970e+07           NaN           NaN           NaN   
3       408.903992  3.686360e+07           NaN           NaN           NaN   
4       398.821014  2.658010e+07    429.916998    429.916998    429.916998   
...            ...           ...           ...           ...           ...   
2428  46760.187500  5.916105e+10  52367.136719  52367.136719  52367.136719   
2429  46456.058594  6.404787e+10  50541.015625  50541.015625  50541.015625   
2430  43537.511719  7.490364e+10  48481.289063  48481.289063  48481.289063   
2431  42909.402344  5.618737e+10  47231.814063  47231.814063  47231.814063   
2432  39321.777344  6.756428e+10  45829.817969  45829.817969  45829.817969   

        close_20ma           y  
0              NaN  -0.0324172  
1              NaN  -0.0314436  
2              NaN   0.0152486  
3              NaN  -0.0108433  
4       429.916998  0.00361221  
...            ...         ...  
2428  52367.136719 -0.00283388  
2429  50541.015625  -0.0281788  
2430  48481.289063 -0.00631114  
2431  47231.814063  -0.0379193  
2432  45829.817969        None  

[2433 rows x 12 columns]

In [40]:
modify_BTC=modify_BTC.dropna()

In [41]:
modify_BTC.head()

Date        Open        High         Low       Close   Adj Close  \
4  2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014   
5  2014-09-22  399.100006  406.915985  397.130005  402.152008  402.152008   
6  2014-09-23  402.092010  441.557007  396.196991  435.790985  435.790985   
7  2014-09-24  435.751007  436.112000  421.131989  423.204987  423.204987   
8  2014-09-25  423.156006  423.519989  409.467987  411.574005  411.574005   

       Volume    open_5ma   close_5ma  close_10ma  close_20ma           y  
4  26580100.0  429.916998  429.916998  429.916998  429.916998  0.00361221  
5  24127600.0  416.564197  416.564197  416.564197  416.564197    0.034888  
6  45099500.0  405.610602  405.610602  405.610602  405.610602  -0.0127275  
7  30627700.0  407.940204  407.940204  407.940204  407.940204  -0.0121028  
8  26814400.0  413.636804  413.636804  413.636804  413.636804 -0.00760996

In [42]:
modify_BTC.tail()

Date          Open          High           Low         Close  \
2427  2021-05-14  49682.980469  51438.117188  48868.578125  49880.535156   
2428  2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429  2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430  2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431  2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   

         Adj Close        Volume      open_5ma     close_5ma    close_10ma  \
2427  49880.535156  5.573750e+10  54046.211719  54046.211719  54046.211719   
2428  46760.187500  5.916105e+10  52367.136719  52367.136719  52367.136719   
2429  46456.058594  6.404787e+10  50541.015625  50541.015625  50541.015625   
2430  43537.511719  7.490364e+10  48481.289063  48481.289063  48481.289063   
2431  42909.402344  5.618737e+10  47231.814063  47231.814063  47231.814063   

        close_20ma           y  
2427  54046.211719  -0.0280549  
2428  52367.136719 -0.00283388  
2429  50541.015625  -0.0281788  
2430  48481.289063 -0.00631114  
2431  47231.814063  -0.0379193

In [43]:
modify_BTC.iloc[:,-5:-1]

open_5ma     close_5ma    close_10ma    close_20ma
4       429.916998    429.916998    429.916998    429.916998
5       416.564197    416.564197    416.564197    416.564197
6       405.610602    405.610602    405.610602    405.610602
7       407.940204    407.940204    407.940204    407.940204
8       413.636804    413.636804    413.636804    413.636804
...            ...           ...           ...           ...
2427  54046.211719  54046.211719  54046.211719  54046.211719
2428  52367.136719  52367.136719  52367.136719  52367.136719
2429  50541.015625  50541.015625  50541.015625  50541.015625
2430  48481.289063  48481.289063  48481.289063  48481.289063
2431  47231.814063  47231.814063  47231.814063  47231.814063

[2428 rows x 4 columns]

In [63]:
X=modify_BTC.iloc[:,-5:-1]

In [45]:
modify_BTC["y"]

4       0.00361221
5         0.034888
6       -0.0127275
7       -0.0121028
8      -0.00760996
           ...    
2427    -0.0280549
2428   -0.00283388
2429    -0.0281788
2430   -0.00631114
2431    -0.0379193
Name: y, Length: 2428, dtype: object

In [46]:
y=modify_BTC["y"]

In [64]:
X.shape

(2428, 4)

In [48]:
y.shape

(2428,)

In [65]:
X.iloc[:1214,:]

open_5ma     close_5ma    close_10ma    close_20ma
4       429.916998    429.916998    429.916998    429.916998
5       416.564197    416.564197    416.564197    416.564197
6       405.610602    405.610602    405.610602    405.610602
7       407.940204    407.940204    407.940204    407.940204
8       413.636804    413.636804    413.636804    413.636804
...            ...           ...           ...           ...
1213  14922.100000  14922.100000  14922.100000  14922.100000
1214  14417.340234  14417.340234  14417.340234  14417.340234
1215  14266.760156  14266.760156  14266.760156  14266.760156
1216  14102.520117  14102.520117  14102.520117  14102.520117
1217  13876.100000  13876.100000  13876.100000  13876.100000

[1214 rows x 4 columns]

In [66]:
X_train = X.iloc[:1214, :]

In [67]:
X.iloc[1214:,:]

open_5ma     close_5ma    close_10ma    close_20ma
1218  13471.539844  13471.539844  13471.539844  13471.539844
1219  12920.819727  12920.819727  12920.819727  12920.819727
1220  12332.619727  12332.619727  12332.619727  12332.619727
1221  11910.399805  11910.399805  11910.399805  11910.399805
1222  11721.019922  11721.019922  11721.019922  11721.019922
...            ...           ...           ...           ...
2427  54046.211719  54046.211719  54046.211719  54046.211719
2428  52367.136719  52367.136719  52367.136719  52367.136719
2429  50541.015625  50541.015625  50541.015625  50541.015625
2430  48481.289063  48481.289063  48481.289063  48481.289063
2431  47231.814063  47231.814063  47231.814063  47231.814063

[1214 rows x 4 columns]

In [68]:
X_test=X.iloc[1214:,:]

In [53]:
y.iloc[:1214]

4       0.00361221
5         0.034888
6       -0.0127275
7       -0.0121028
8      -0.00760996
           ...    
1213     0.0116347
1214    -0.0181635
1215    0.00150474
1216    -0.0801628
1217    -0.0115632
Name: y, Length: 1214, dtype: object

In [54]:
y_train=y.iloc[:1214]

In [55]:
y.iloc[1214:]

1218     0.0109732
1219    0.00498604
1220     0.0458278
1221    -0.0461011
1222    -0.0257859
           ...    
2427    -0.0280549
2428   -0.00283388
2429    -0.0281788
2430   -0.00631114
2431    -0.0379193
Name: y, Length: 1214, dtype: object

In [56]:
y_test=y.iloc[1214:]

In [69]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1214, 4)
(1214, 4)
(1214,)
(1214,)


In [57]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [70]:
reg = LinearRegression().fit(X_train, y_train)

In [71]:
reg.predict(X_train)

array([0.00113122, 0.00113054, 0.00112999, ..., 0.00182812, 0.00181985,
       0.00180844])

In [72]:
reg.predict(X_train).size

1214

In [73]:
y_train.to_numpy()

array([0.0036122081854804973, 0.03488800042486006, -0.01272746522596057,
       ..., 0.0015047378178780961, -0.08016282477089828,
       -0.011563194451440566], dtype=object)

In [74]:
from sklearn.metrics import mean_squared_error

In [75]:
y_true_train = y_train.to_numpy()
y_pred_train = reg.predict(X_train)
print("regression train mse: ", round(mean_squared_error(y_true_train, y_pred_train), 10))

regression train mse:  0.000281698


In [76]:
y_true_test = y_test.to_numpy()
y_pred_test = reg.predict(X_test)
print("regression test mse: ", round(mean_squared_error(y_true_test, y_pred_test), 10))

regression test mse:  0.0003019617


In [77]:
result = []
row = []
row.append("regression train mse: ")
row.append(round(mean_squared_error(y_true_train, y_pred_train), 10))
result.append(row)
row = []
row.append("regression test mse: ")
row.append(round(mean_squared_error(y_true_test, y_pred_test), 10))
result.append(row)
pd.DataFrame(result)

0         1
0  regression train mse:   0.000282
1   regression test mse:   0.000302